Add base degen vault
AffineLabs/defi-sdk pull request #154
Opened 2023-09-21 18:35 UTC by maruf0011

2023-09-22 00:02 UTC, larryob requested changes
This should actually replace `baseUsdcEarn`. Also, the dist folder changes seem odd.

2023-09-22 15:03 UTC, maruf0011 commented
Dropped BaseUsdEarn.

2023-09-22 16:03 UTC, pchy10 approved these changes

2024-12-13 23:05 UTC, tmoon commented
abandoned

2024-12-13 23:05 UTC, closed without merging